version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: selenium
    versions:
    - 4.0.0.b1
    - 4.0.0.b2
    - 4.0.0.b2.post1
